using System;
using System.Collections.Generic;
using System.Text;
using TinyPinyin;

namespace PinYinSearch_ONI_MOD
{
    public class searchPinYin
    {
        ///<summary>
        ///返回拼音，首先在字典里查询，如果字典里没有会调用拼音转换函数
        ///</summary>
        ///<param name="text">需要被转换的汉字</param>
        ///<returns>返回的拼音以及首字母，全小写，拼音和首字母之间会用[空格]隔开</returns>
        public static string getPinYin(string text)
        {
            Dictionary<string, string[]> dict = pinYinDict.Dict;
            string pinYin = null;
            string[] pinYinTemp = null;
            if (pinYinDict.Dict.TryGetValue(chineseFilter(text), out pinYinTemp))
            {
                pinYin = pinYinTemp[1] + " " + pinYinTemp[0];
            }
            else
            {
                pinYin = generatePinYin(text);
            }
            return pinYin;
        }

        ///<summary>
        ///把汉字转换成拼音，如果输入的是英文的话会被去除空格后返回
        ///</summary>
        ///<param name="text">需要被转换的汉字</param>
        ///<returns>返回的拼音以及首字母，全小写，拼音和首字母之间会用[空格]隔开</returns>
        private static string generatePinYin(string text)
        {
            string chineseText = chineseFilter(text);
            string buildingPinYin = null;

            //如果有中文
            if (chineseText.Length > 0)
            {
                string pinYinTemp1 = PinyinHelper.GetPinyinInitials(chineseText).Replace(" ", "");
                string pinYinTemp2 = PinyinHelper.GetPinyin(chineseText).Replace(" ", "");
                buildingPinYin = pinYinTemp1 + " " + pinYinTemp2;
            }
            else
            {
                //英文情况
                buildingPinYin = text;
            }
            return buildingPinYin.ToLower();
        }

        ///<summary>
        ///过滤非中文
        ///</summary>
        ///<param name="text">需要被过滤的文本</param>
        ///<returns>返回string内的所有中文，如果没有中文的话会返回一个空string</returns>
        private static string chineseFilter(string line)
        {
            if (string.IsNullOrEmpty(line))
            {
                return "";
            }

            StringBuilder sb = null;

            foreach (char ch in line)
            {
                if (PinyinHelper.IsChinese(ch))
                {
                    if (sb == null)
                    {
                        sb = new StringBuilder(line.Length);
                    }
                    sb.Append(ch);
                }
            }

            if (sb == null)
            {
                return "";
            }
            return sb.ToString();
        }
    }

    public static class pinYinDict
    {
        public static readonly Dictionary<string, string[]> Dict = InitializeDict();

        ///<summary>
        ///根据科雷的.po本地化文件创建的字典
        ///generate_pinyin_dict.py
        ///</summary>
        ///<returns>返回的字典</returns>
        public static Dictionary<string, string[]> InitializeDict()
        {
            Dictionary<string, string[]> Dict = new Dictionary<string, string[]>(800);
            //Debug.Log("[PinYinDev] Create Pinyin Dict");

            Dict.Add("核能配药桌", new string[] { "henengpeiyaozhuo", "hnpyz" });
            Dict.Add("焊接台", new string[] { "hanjietai", "hjt" });
            Dict.Add("病诊站", new string[] { "bingzhenzhan", "bzz" });
            Dict.Add("超级计算机", new string[] { "chaojijisuanji", "cjjsj" });
            Dict.Add("飞行小动物诱惑器", new string[] { "feixingxiaodongwuyouhuoqi", "fxxdwyhq" });
            Dict.Add("飞行小动物公寓", new string[] { "feixingxiaodongwugongyu", "fxxdwgy" });
            Dict.Add("温度调节器", new string[] { "wendutiaojieqi", "wdtjq" });
            Dict.Add("空气净化器", new string[] { "kongqijinghuaqi", "kqjhq" });
            Dict.Add("藻类蒸馏器", new string[] { "zaoleizhengliuqi", "zlzlq" });
            Dict.Add("藻类箱", new string[] { "zaoleixiang", "zlx" });
            Dict.Add("配药桌", new string[] { "peiyaozhuo", "pyz" });
            Dict.Add("游戏机台", new string[] { "youxijitai", "yxjt" });
            Dict.Add("工艺品分析站", new string[] { "gongyipinfenxizhan", "gypfxz" });
            Dict.Add("工艺品运输舱", new string[] { "gongyipinyunshucang", "gypysc" });
            Dict.Add("太空学员离心机", new string[] { "taikongxueyuanlixinji", "tkxylxj" });
            Dict.Add("自动采矿机", new string[] { "zidongcaikuangji", "zdckj" });
            Dict.Add("蓄电池", new string[] { "xudianchi", "xdc" });
            Dict.Add("巨型蓄电池", new string[] { "juxingxudianchi", "jxxdc" });
            Dict.Add("蓄电池舱", new string[] { "xudianchicang", "xdcc" });
            Dict.Add("智能蓄电池", new string[] { "zhinengxudianchi", "znxdc" });
            Dict.Add("沙滩椅", new string[] { "shatanyi", "sty" });
            Dict.Add("床铺", new string[] { "chuangpu", "cp" });
            Dict.Add("辐射蜂巢", new string[] { "fushefengchao", "fsfc" });
            Dict.Add("生物柴油引擎", new string[] { "shengwuchaiyouyinqing", "swcyyq" });
            Dict.Add("液桶排倒器", new string[] { "yetongpaidaoqi", "ytpdq" });
            Dict.Add("气罐抽出器", new string[] { "qiguanchouchuqi", "qgccq" });
            Dict.Add("液桶抽出器", new string[] { "yetongchouchuqi", "ytccq" });
            Dict.Add("气罐排倒器", new string[] { "qiguanpaidaoqi", "qgpdq" });
            Dict.Add("地堡门", new string[] { "dibaomen", "dbm" });
            Dict.Add("地堡砖", new string[] { "dibaozhuan", "dbz" });
            Dict.Add("柴火炉", new string[] { "chaihuolu", "chl" });
            Dict.Add("空白画布", new string[] { "kongbaihuabu", "kbhb" });
            Dict.Add("肖像画布", new string[] { "xiaoxianghuabu", "xxhb" });
            Dict.Add("风景画布", new string[] { "fengjinghuabu", "fjhb" });
            Dict.Add("货舱", new string[] { "huocang", "hc" });
            Dict.Add("大型货舱", new string[] { "daxinghuocang", "dxhc" });
            Dict.Add("地毯砖", new string[] { "ditanzhuan", "dtz" });
            Dict.Add("垂吊化石雕塑块", new string[] { "chuidiaohuashidiaosukuai", "cdhsdsk" });
            Dict.Add("吸顶灯", new string[] { "xidingdeng", "xdd" });
            Dict.Add("复制人检查站", new string[] { "fuzhirenjianchazhan", "fzrjcz" });
            Dict.Add("乳化器", new string[] { "ruhuaqi", "rhq" });
            Dict.Add("漂白石料斗", new string[] { "piaobaishiliaodou", "pbsld" });
            Dict.Add("时装翻新器", new string[] { "shizhuangfanxinqi", "szfxq" });
            Dict.Add("纺织机", new string[] { "fangzhiji", "fzj" });
            Dict.Add("指挥舱", new string[] { "zhihuicang", "zhc" });
            Dict.Add("内部舱门", new string[] { "neibucangmen", "nbcm" });
            Dict.Add("望远镜", new string[] { "wangyuanjing", "wyj" });
            Dict.Add("隔绝式望远镜", new string[] { "gejueshiwangyuanjing", "gjswyj" });
            Dict.Add("二氧化碳引擎", new string[] { "eryanghuatanyinqing", "eyhtyq" });
            Dict.Add("碳素脱离器", new string[] { "tansutuoliqi", "tstlq" });
            Dict.Add("太空扫描仪", new string[] { "taikongsaomiaoyi", "tksmy" });
            Dict.Add("堆肥堆", new string[] { "duifeidui", "dfd" });
            Dict.Add("标记待清空", new string[] { "biaojidaiqingkong", "bjdqk" });
            Dict.Add("导热板", new string[] { "daoreban", "drb" });
            Dict.Add("电动烤炉", new string[] { "diandongkaolu", "ddkl" });
            Dict.Add("边角饰件", new string[] { "bianjiaoshijian", "bjsj" });
            Dict.Add("虚拟天象仪", new string[] { "xunitianxiangyi", "xntxy" });
            Dict.Add("工作台", new string[] { "gongzuotai", "gzt" });
            Dict.Add("飞行小动物陷阱", new string[] { "feixingxiaodongwuxianjing", "fxxdwxj" });
            Dict.Add("小动物放生点", new string[] { "xiaodongwufangshengdian", "xdwfsd" });
            Dict.Add("小动物喂食器", new string[] { "xiaodongwuweishiqi", "xdwwsq" });
            Dict.Add("小动物陷阱", new string[] { "xiaodongwuxianjing", "xdwxj" });
            Dict.Add("小动物公寓", new string[] { "xiaodongwugongyu", "xdwgy" });
            Dict.Add("小动物移取点", new string[] { "xiaodongwuyiqudian", "xdwyqd" });
            Dict.Add("天花板饰件", new string[] { "tianhuabanshijian", "thbsj" });
            Dict.Add("低温箱3000", new string[] { "diwenxiang3000", "dwx3000" });
            Dict.Add("数据挖掘仪", new string[] { "shujuwajueyi", "sjwjy" });
            Dict.Add("除污淋浴隔间", new string[] { "chuwulinyugejian", "cwlygj" });
            Dict.Add("油炸锅", new string[] { "youzhaguo", "yzg" });
            Dict.Add("处于厨房之外", new string[] { "chuyuchufangzhiwai", "cycfzw" });
            Dict.Add("脱盐器", new string[] { "tuoyanqi", "tyq" });
            Dict.Add("开发者发电机", new string[] { "kaifazhefadianji", "kfzfdj" });
            Dict.Add("开发者加热器", new string[] { "kaifazhejiareqi", "kfzjrq" });
            Dict.Add("开发者辐射粒子生成器", new string[] { "kaifazhefushelizishengchengqi", "kfzfslzscq" });
            Dict.Add("开发者维生器", new string[] { "kaifazheweishengqi", "kfzwsq" });
            Dict.Add("开发者光源", new string[] { "kaifazheguangyuan", "kfzgy" });
            Dict.Add("开发者气泵", new string[] { "kaifazheqibeng", "kfzqb" });
            Dict.Add("开发者液泵", new string[] { "kaifazheyebeng", "kfzyb" });
            Dict.Add("开发者固体泵", new string[] { "kaifazhegutibeng", "kfzgtb" });
            Dict.Add("开发者辐射释放器", new string[] { "kaifazhefusheshifangqi", "kfzfssfq" });
            Dict.Add("钻石压机", new string[] { "zuanshiyaji", "zsyj" });
            Dict.Add("小餐桌", new string[] { "xiaocanzhuo", "xcz" });
            Dict.Add("液渠", new string[] { "yequ", "yq" });
            Dict.Add("蒸馏塔", new string[] { "zhengliuta", "zlt" });
            Dict.Add("研究信息传送通道", new string[] { "yanjiuxinxichuansongtongdao", "yjxxcstd" });
            Dict.Add("医务站", new string[] { "yiwuzhan", "ywz" });
            Dict.Add("自动", new string[] { "zidong", "zd" });
            Dict.Add("锁定", new string[] { "suoding", "sd" });
            Dict.Add("开启", new string[] { "kaiqi", "kq" });
            Dict.Add("气动门", new string[] { "qidongmen", "qdm" });
            Dict.Add("敲蛋桌", new string[] { "qiaodanzhuo", "qdz" });
            Dict.Add("孵化器", new string[] { "fuhuaqi", "fhq" });
            Dict.Add("移动电源充电机", new string[] { "yidongdianyuanchongdianji", "yddycdj" });
            Dict.Add("电解器", new string[] { "dianjieqi", "djq" });
            Dict.Add("逃生舱", new string[] { "taoshengcang", "tsc" });
            Dict.Add("浓缩咖啡机", new string[] { "nongsuokafeiji", "nskfj" });
            Dict.Add("乙醇蒸馏器", new string[] { "yichunzhengliuqi", "yczlq" });
            Dict.Add("迷你舱", new string[] { "minicang", "mnc" });
            Dict.Add("干板墙", new string[] { "ganbanqiang", "gbq" });
            Dict.Add("胶合板压机", new string[] { "jiaohebanyaji", "jhbyj" });
            Dict.Add("窗户", new string[] { "chuanghu", "ch" });
            Dict.Add("农业站", new string[] { "nongyezhan", "nyz" });
            Dict.Add("土培砖", new string[] { "tupeizhuan", "tpz" });
            Dict.Add("肥料合成器", new string[] { "feiliaohechengqi", "flhcq" });
            Dict.Add("消防滑杆", new string[] { "xiaofanghuagan", "xfhg" });
            Dict.Add("鱼类放生点", new string[] { "yuleifangshengdian", "ylfsd" });
            Dict.Add("喂鱼器", new string[] { "weiyuqi", "wyq" });
            Dict.Add("鱼类移取点", new string[] { "yuleiyiqudian", "ylyqd" });
            Dict.Add("捕鱼陷阱", new string[] { "buyuxianjing", "byxj" });
            Dict.Add("电灯", new string[] { "diandeng", "dd" });
            Dict.Add("压力板", new string[] { "yaliban", "ylb" });
            Dict.Add("花盆", new string[] { "huapen", "hp" });
            Dict.Add("垂吊花盆", new string[] { "chuidiaohuapen", "cdhp" });
            Dict.Add("透明花盆", new string[] { "touminghuapen", "tmhp" });
            Dict.Add("墙壁花盆", new string[] { "qiangbihuapen", "qbhp" });
            Dict.Add("抽水马桶", new string[] { "choushuimatong", "csmt" });
            Dict.Add("飞行小动物诱饵", new string[] { "feixingxiaodongwuyouer", "fxxdwye" });
            Dict.Add("脱水机", new string[] { "tuoshuiji", "tsj" });
            Dict.Add("充水机", new string[] { "chongshuiji", "csj" });
            Dict.Add("远古标本", new string[] { "yuangubiaoben", "ygbb" });
            Dict.Add("化石采集场", new string[] { "huashicaijichang", "hscjc" });
            Dict.Add("化石雕塑块", new string[] { "huashidiaosukuai", "hsdsk" });
            Dict.Add("自来水笔", new string[] { "zilaishuibi", "zlsb" });
            Dict.Add("伽马射线烤炉", new string[] { "gamashexiankaolu", "gmsxkl" });
            Dict.Add("通行支架", new string[] { "tongxingzhijia", "txzj" });
            Dict.Add("气体装罐器", new string[] { "qitizhuangguanqi", "qtzgq" });
            Dict.Add("气罐货舱", new string[] { "qiguanhuocang", "qghc" });
            Dict.Add("大型气罐货舱", new string[] { "daxingqiguanhuocang", "dxqghc" });
            Dict.Add("气体管道", new string[] { "qitiguandao", "qtgd" });
            Dict.Add("气体管桥", new string[] { "qitiguanqiao", "qtgq" });
            Dict.Add("气体管道病菌传感器", new string[] { "qitiguandaobingjunchuanganqi", "qtgdbjcgq" });
            Dict.Add("气体管道元素传感器", new string[] { "qitiguandaoyuansuchuanganqi", "qtgdyscgq" });
            Dict.Add("气体溢流阀", new string[] { "qitiyiliufa", "qtylf" });
            Dict.Add("优先气流阀", new string[] { "youxianqiliufa", "yxqlf" });
            Dict.Add("导热气体管道", new string[] { "daoreqitiguandao", "drqtgd" });
            Dict.Add("气体管道温度传感器", new string[] { "qitiguandaowenduchuanganqi", "qtgdwdcgq" });
            Dict.Add("气体筛选器", new string[] { "qitishaixuanqi", "qtsxq" });
            Dict.Add("气体计量阀", new string[] { "qitijiliangfa", "qtjlf" });
            Dict.Add("气体截断阀", new string[] { "qitijieduanfa", "qtjdf" });
            Dict.Add("小型气泵", new string[] { "xiaoxingqibeng", "xxqb" });
            Dict.Add("透气砖", new string[] { "touqizhuan", "tqz" });
            Dict.Add("气泵", new string[] { "qibeng", "qb" });
            Dict.Add("储气库", new string[] { "chuqiku", "cqk" });
            Dict.Add("气体调节阀", new string[] { "qititiaojiefa", "qttjf" });
            Dict.Add("排气口", new string[] { "paiqikou", "pqk" });
            Dict.Add("高压排气口", new string[] { "gaoyapaiqikou", "gypqk" });
            Dict.Add("煤炭发电机", new string[] { "meitanfadianji", "mtfdj" });
            Dict.Add("全能打印机", new string[] { "quannengdayinji", "qndyj" });
            Dict.Add("神经振荡仪", new string[] { "shenjingzhendangyi", "sjzdy" });
            Dict.Add("植物分析仪", new string[] { "zhiwufenxiyi", "zwfxy" });
            Dict.Add("地热热泵", new string[] { "direrebeng", "drrb" });
            Dict.Add("地热排气口", new string[] { "direpaiqikou", "drpqk" });
            Dict.Add("地热排气口 C-{ID}", new string[] { "direpaiqikou C-{ID}", "drpqk C-{ID}" });
            Dict.Add("地质调谐仪", new string[] { "dizhitiaoxieyi", "dztxy" });
            Dict.Add("玻璃吸顶灯", new string[] { "bolixidingdeng", "blxdd" });
            Dict.Add("玻璃背景墙", new string[] { "bolibeijingqiang", "blbjq" });
            Dict.Add("玻璃熔炉", new string[] { "bolironglu", "blrl" });
            Dict.Add("窗户砖", new string[] { "chuanghuzhuan", "chz" });
            Dict.Add("燃气灶", new string[] { "ranqizao", "rqz" });
            Dict.Add("雅致的纪念碑", new string[] { "yazhidejinianbei", "yzdjnb" });
            Dict.Add("马桶", new string[] { "matong", "mt" });
            Dict.Add("睡衣储柜", new string[] { "shuiyichugui", "sycg" });
            Dict.Add("小动物衍变器", new string[] { "xiaodongwuyanbianqi", "xdwybq" });
            Dict.Add("庄严科技门", new string[] { "zhuangyankejimen", "zykjm" });
            Dict.Add("LED灯", new string[] { "LEDdeng", "LEDd" });
            Dict.Add("庄严科技基座", new string[] { "zhuangyankejijizuo", "zykjjz" });
            Dict.Add("粘渣油提取器", new string[] { "zhanzhayoutiquqi", "zzytqq" });
            Dict.Add("太空员舱", new string[] { "taikongyuancang", "tkyc" });
            Dict.Add("单太空员前锥", new string[] { "dantaikongyuanqianzhui", "dtkyqz" });
            Dict.Add("手部消毒站", new string[] { "shoubuxiaoduzhan", "sbxdz" });
            Dict.Add("打印舱", new string[] { "dayincang", "dyc" });
            Dict.Add("液体均热器", new string[] { "yetijunreqi", "ytjrq" });
            Dict.Add("辐射粒子蓄存器", new string[] { "fushelizixucunqi", "fslzxcq" });
            Dict.Add("辐射粒子接合板", new string[] { "fushelizijieheban", "fslzjhb" });
            Dict.Add("辐射粒子引擎", new string[] { "fusheliziyinqing", "fslzyq" });
            Dict.Add("辐射粒子变向器", new string[] { "fushelizibianxiangqi", "fslzbxq" });
            Dict.Add("辐射粒子发生器", new string[] { "fushelizifashengqi", "fslzfsq" });
            Dict.Add("高负荷电线", new string[] { "gaofuhedianxian", "gfhdx" });
            Dict.Add("打印截能仪", new string[] { "dayinjienengyi", "dyjny" });
            Dict.Add("热水浴缸", new string[] { "reshuiyugang", "rsyg" });
            Dict.Add("液氢引擎", new string[] { "yeqingyinqing", "yqyq" });
            Dict.Add("氢气发电机", new string[] { "qingqifadianji", "qqfdj" });
            Dict.Add("液培砖", new string[] { "yepeizhuan", "ypz" });
            Dict.Add("冰冷风扇", new string[] { "binglengfengshan", "blfs" });
            Dict.Add("融冰壶", new string[] { "rongbinghu", "rbh" });
            Dict.Add("制冰机", new string[] { "zhibingji", "zbj" });
            Dict.Add("冰雕塑块", new string[] { "bingdiaosukuai", "bdsk" });
            Dict.Add("隔热门", new string[] { "geremen", "grm" });
            Dict.Add("隔热气体管道", new string[] { "gereqitiguandao", "grqtgd" });
            Dict.Add("隔热液体管道", new string[] { "gereyetiguandao", "grytgd" });
            Dict.Add("隔热电线", new string[] { "geredianxian", "grdx" });
            Dict.Add("隔热砖", new string[] { "gerezhuan", "grz" });
            Dict.Add("基座", new string[] { "jizuo", "jz" });
            Dict.Add("喷气服存放柜", new string[] { "penqifucunfanggui", "pqfcfg" });
            Dict.Add("喷气服检查站", new string[] { "penqifujianchazhan", "pqfjcz" });
            Dict.Add("榨汁机", new string[] { "zhazhiji", "zzj" });
            Dict.Add("石油引擎", new string[] { "shiyouyinqing", "syyq" });
            Dict.Add("小型石油引擎", new string[] { "xiaoxingshiyouyinqing", "xxsyyq" });
            Dict.Add("窑炉", new string[] { "yaolu", "yl" });
            Dict.Add("梯子", new string[] { "tizi", "tz" });
            Dict.Add("梯床", new string[] { "tichuang", "tc" });
            Dict.Add("塑料梯子", new string[] { "suliaotizi", "sltz" });
            Dict.Add("太空员部署舱", new string[] { "taikongyuanbushucang", "tkybsc" });
            Dict.Add("定位信标", new string[] { "dingweixinbiao", "dwxb" });
            Dict.Add("墙壁种植箱", new string[] { "qiangbizhongzhixiang", "qbzzx" });
            Dict.Add("大型放电器", new string[] { "daxingfangdianqi", "dxfdq" });
            Dict.Add("火箭平台", new string[] { "huojianpingtai", "hjpt" });
            Dict.Add("铅服存放柜", new string[] { "qianfucunfanggui", "qfcfg" });
            Dict.Add("铅服检查站", new string[] { "qianfujianchazhan", "qfjcz" });
            Dict.Add("液体装桶器", new string[] { "yetizhuangtongqi", "ytztq" });
            Dict.Add("液缸货舱", new string[] { "yeganghuocang", "yghc" });
            Dict.Add("大型液缸货舱", new string[] { "daxingyeganghuocang", "dxyghc" });
            Dict.Add("液温调节器", new string[] { "yewentiaojieqi", "ywtjq" });
            Dict.Add("液体管道", new string[] { "yetiguandao", "ytgd" });
            Dict.Add("液体管桥", new string[] { "yetiguanqiao", "ytgq" });
            Dict.Add("液体管道病菌传感器", new string[] { "yetiguandaobingjunchuanganqi", "ytgdbjcgq" });
            Dict.Add("液体管道元素传感器", new string[] { "yetiguandaoyuansuchuanganqi", "ytgdyscgq" });
            Dict.Add("液体溢流阀", new string[] { "yetiyiliufa", "ytylf" });
            Dict.Add("优先液流阀", new string[] { "youxianyeliufa", "yxylf" });
            Dict.Add("导热液体管道", new string[] { "daoreyetiguandao", "drytgd" });
            Dict.Add("液体管道温度传感器", new string[] { "yetiguandaowenduchuanganqi", "ytgdwdcgq" });
            Dict.Add("水冷风扇", new string[] { "shuilengfengshan", "slfs" });
            Dict.Add("液体筛选器", new string[] { "yetishaixuanqi", "ytsxq" });
            Dict.Add("液缸燃料舱", new string[] { "yegangranliaocang", "ygrlc" });
            Dict.Add("大型液缸燃料舱", new string[] { "daxingyegangranliaocang", "dxygrlc" });
            Dict.Add("液体加热器", new string[] { "yetijiareqi", "ytjrq" });
            Dict.Add("液体计量阀", new string[] { "yetijiliangfa", "ytjlf" });
            Dict.Add("液体截断阀", new string[] { "yetijieduanfa", "ytjdf" });
            Dict.Add("小型液泵", new string[] { "xiaoxingyebeng", "xxyb" });
            Dict.Add("液泵", new string[] { "yebeng", "yb" });
            Dict.Add("手压泵", new string[] { "shouyabeng", "syb" });
            Dict.Add("储液库", new string[] { "chuyeku", "cyk" });
            Dict.Add("液体调节阀", new string[] { "yetitiaojiefa", "yttjf" });
            Dict.Add("排液口", new string[] { "paiyekou", "pyk" });
            Dict.Add("砂盆", new string[] { "shapen", "sp" });
            Dict.Add("自动化通知器", new string[] { "zidonghuatongzhiqi", "zdhtzq" });
            Dict.Add("星图位置传感器", new string[] { "xingtuweizhichuanganqi", "xtwzcgq" });
            Dict.Add("信号计数器", new string[] { "xinhaojishuqi", "xhjsq" });
            Dict.Add("小动物传感器", new string[] { "xiaodongwuchuanganqi", "xdwcgq" });
            Dict.Add("病菌传感器", new string[] { "bingjunchuanganqi", "bjcgq" });
            Dict.Add("复制人运动传感器", new string[] { "fuzhirenyundongchuanganqi", "fzrydcgq" });
            Dict.Add("气体元素传感器", new string[] { "qitiyuansuchuanganqi", "qtyscgq" });
            Dict.Add("液体元素传感器", new string[] { "yetiyuansuchuanganqi", "ytyscgq" });
            Dict.Add("与门", new string[] { "yumen", "ym" });
            Dict.Add("缓冲门", new string[] { "huanchongmen", "hcm" });
            Dict.Add("信号分配器", new string[] { "xinhaofenpeiqi", "xhfpq" });
            Dict.Add("过滤门", new string[] { "guolvmen", "glm" });
            Dict.Add("信号选择器", new string[] { "xinhaoxuanzeqi", "xhxzq" });
            Dict.Add("非门", new string[] { "feimen", "fm" });
            Dict.Add("或门", new string[] { "huomen", "hm" });
            Dict.Add("异或门", new string[] { "yihuomen", "yhm" });
            Dict.Add("音槌", new string[] { "yinchui", "yc" });
            Dict.Add("辐射粒子传感器", new string[] { "fushelizichuanganqi", "fslzcgq" });
            Dict.Add("信号接收器", new string[] { "xinhaojieshouqi", "xhjsq" });
            Dict.Add("信号播报器", new string[] { "xinhaobobaoqi", "xhbbq" });
            Dict.Add("光线传感器", new string[] { "guangxianchuanganqi", "gxcgq" });
            Dict.Add("锁存器", new string[] { "suocunqi", "scq" });
            Dict.Add("电力截断器", new string[] { "dianlijieduanqi", "dljdq" });
            Dict.Add("气压传感器", new string[] { "qiyachuanganqi", "qycgq" });
            Dict.Add("液压传感器", new string[] { "yeyachuanganqi", "yycgq" });
            Dict.Add("辐射传感器", new string[] { "fushechuanganqi", "fscgq" });
            Dict.Add("信号线组", new string[] { "xinhaoxianzu", "xhxz" });
            Dict.Add("信号线组桥", new string[] { "xinhaoxianzuqiao", "xhxzq" });
            Dict.Add("线组读取器", new string[] { "xianzuduquqi", "xzdqq" });
            Dict.Add("线组写入器", new string[] { "xianzuxieruqi", "xzxrq" });
            Dict.Add("信号开关", new string[] { "xinhaokaiguan", "xhkg" });
            Dict.Add("温度传感器", new string[] { "wenduchuanganqi", "wdcgq" });
            Dict.Add("周期传感器", new string[] { "zhouqichuanganqi", "zqcgq" });
            Dict.Add("时间传感器", new string[] { "shijianchuanganqi", "sjcgq" });
            Dict.Add("功率传感器", new string[] { "gonglvchuanganqi", "glcgq" });
            Dict.Add("信号线", new string[] { "xinhaoxian", "xhx" });
            Dict.Add("信号线桥", new string[] { "xinhaoxianqiao", "xhxq" });
            Dict.Add("邮箱", new string[] { "youxiang", "yx" });
            Dict.Add("庄严科技运输集装箱", new string[] { "zhuangyankejiyunshujizhuangxiang", "zykjysjzx" });
            Dict.Add("舒适的床", new string[] { "shushidechuang", "ssdc" });
            Dict.Add("机械站", new string[] { "jixiezhan", "jxz" });
            Dict.Add("人力发电机", new string[] { "renlifadianji", "rlfdj" });
            Dict.Add("人力辐射粒子发生器", new string[] { "renlifushelizifashengqi", "rlfslzfsq" });
            Dict.Add("手动气闸", new string[] { "shoudongqizha", "sdqz" });
            Dict.Add("大理石雕塑块", new string[] { "dalishidiaosukuai", "dlsdsk" });
            Dict.Add("按摩床", new string[] { "anmochuang", "amc" });
            Dict.Add("反熵热量中和器", new string[] { "fanshangreliangzhongheqi", "fsrlzhq" });
            Dict.Add("机械冲浪板", new string[] { "jixiechonglangban", "jxclb" });
            Dict.Add("分诊床", new string[] { "fenzhenchuang", "fzc" });
            Dict.Add("梦境合成仪", new string[] { "mengjinghechengyi", "mjhcy" });
            Dict.Add("汞吸顶灯", new string[] { "gongxidingdeng", "gxdd" });
            Dict.Add("网格砖", new string[] { "wanggezhuan", "wgz" });
            Dict.Add("金属精炼器", new string[] { "jinshujinglianqi", "jsjlq" });
            Dict.Add("金属雕塑块", new string[] { "jinshudiaosukuai", "jsdsk" });
            Dict.Add("金属砖", new string[] { "jinshuzhuan", "jsz" });
            Dict.Add("天然气发电机", new string[] { "tianranqifadianji", "trqfdj" });
            Dict.Add("食物压制器", new string[] { "shiwuyazhiqi", "swyzq" });
            Dict.Add("提炼器", new string[] { "tilianqi", "tlq" });
            Dict.Add("小动物直饮器", new string[] { "xiaodongwuzhiyinqi", "xdwzyq" });
            Dict.Add("挤奶站", new string[] { "jinaizhan", "jnz" });
            Dict.Add("植物粉碎机", new string[] { "zhiwufensuiji", "zwfsj" });
            Dict.Add("氧气扩散器", new string[] { "yangqikuosanqi", "yqksq" });
            Dict.Add("小型冰箱", new string[] { "xiaoxingbingxiang", "xxbx" });
            Dict.Add("未知复制人", new string[] { "weizhifuzhiren", "wzfzr" });
            Dict.Add("爆破弹组装机", new string[] { "baopodanzuzhuangji", "bpdzzj" });
            Dict.Add("流星爆破炮", new string[] { "liuxingbaopopao", "lxbpp" });
            Dict.Add("炸药储物柜", new string[] { "zhayaochuwugui", "zycwg" });
            Dict.Add("航天指挥站", new string[] { "hangtianzhihuizhan", "htzhz" });
            Dict.Add("气体输入枢纽", new string[] { "qitishurushuniu", "qtsrsn" });
            Dict.Add("火箭端口", new string[] { "huojianduankou", "hjdk" });
            Dict.Add("火箭端口延伸桥", new string[] { "huojianduankouyanshenqiao", "hjdkysq" });
            Dict.Add("火箭端口气体装载器", new string[] { "huojianduankouqitizhuangzaiqi", "hjdkqtzzq" });
            Dict.Add("火箭端口气体卸载器", new string[] { "huojianduankouqitixiezaiqi", "hjdkqtxzq" });
            Dict.Add("火箭端口液体装载器", new string[] { "huojianduankouyetizhuangzaiqi", "hjdkytzzq" });
            Dict.Add("火箭端口液体卸载器", new string[] { "huojianduankouyetixiezaiqi", "hjdkytxzq" });
            Dict.Add("火箭端口固体装载器", new string[] { "huojianduankougutizhuangzaiqi", "hjdkgtzzq" });
            Dict.Add("火箭端口固体卸载器", new string[] { "huojianduankougutixiezaiqi", "hjdkgtxzq" });
            Dict.Add("液体输入枢纽", new string[] { "yetishurushuniu", "ytsrsn" });
            Dict.Add("固体输入枢纽", new string[] { "gutishurushuniu", "gtsrsn" });
            Dict.Add("丰碑底基", new string[] { "fengbeidiji", "fbdj" });
            Dict.Add("丰碑中段", new string[] { "fengbeizhongduan", "fbzd" });
            Dict.Add("丰碑顶部", new string[] { "fengbeidingbu", "fbdb" });
            Dict.Add("生机组构仪", new string[] { "shengjizugouyi", "sjzgy" });
            Dict.Add("镶边砖", new string[] { "xiangbianzhuan", "xbz" });
            Dict.Add("公用餐桌", new string[] { "gongyongcanzhuo", "gycz" });
            Dict.Add("基础前锥", new string[] { "jichuqianzhui", "jcqz" });
            Dict.Add("钻头前锥", new string[] { "zuantouqianzhui", "ztqz" });
            Dict.Add("研究性反应堆", new string[] { "yanjiuxingfanyingdui", "yjxfyd" });
            Dict.Add("材料研究终端", new string[] { "cailiaoyanjiuzhongduan", "clyjzd" });
            Dict.Add("自动卸物箱", new string[] { "zidongxiewuxiang", "zdxwx" });
            Dict.Add("润滑站", new string[] { "runhuazhan", "rhz" });
            Dict.Add("原油精炼器", new string[] { "yuanyoujinglianqi", "yyjlq" });
            Dict.Add("油井", new string[] { "youjing", "yj" });
            Dict.Add("环轨货舱", new string[] { "huanguihuocang", "hghc" });
            Dict.Add("轨道数据收集实验仪", new string[] { "guidaoshujushoujishiyanyi", "gdsjsjsyy" });
            Dict.Add("矿石洗涤器", new string[] { "kuangshixidiqi", "ksxdq" });
            Dict.Add("户外厕所", new string[] { "huwaicesuo", "hwcs" });
            Dict.Add("固体氧化剂舱", new string[] { "gutiyanghuajicang", "gtyhjc" });
            Dict.Add("大型固体氧化剂舱", new string[] { "daxinggutiyanghuajicang", "dxgtyhjc" });
            Dict.Add("液体氧化剂舱", new string[] { "yetiyanghuajicang", "ytyhjc" });
            Dict.Add("氧气面罩存放柜", new string[] { "yangqimianzhaocunfanggui", "yqmzcfg" });
            Dict.Add("氧气面罩检查站", new string[] { "yangqimianzhaojianchazhan", "yqmzjcz" });
            Dict.Add("氧气面罩站", new string[] { "yangqimianzhaozhan", "yqmzz" });
            Dict.Add("氧石精炼炉", new string[] { "yangshijinglianlu", "ysjll" });
            Dict.Add("氧石烛台", new string[] { "yangshizhutai", "yszt" });
            Dict.Add("公园标识", new string[] { "gongyuanbiaoshi", "gybs" });
            Dict.Add("三层蛋糕", new string[] { "sancengdangao", "scdg" });
            Dict.Add("泥炭燃烧器", new string[] { "nitanranshaoqi", "ntrsq" });
            Dict.Add("石油发电机", new string[] { "shiyoufadianji", "syfdj" });
            Dict.Add("点唱机器人", new string[] { "dianchangjiqiren", "dcjqr" });
            Dict.Add("先锋着陆器", new string[] { "xianfengzhuoluqi", "xfzlq" });
            Dict.Add("先锋舱", new string[] { "xianfengcang", "xfc" });
            Dict.Add("像素屏", new string[] { "xiangsuping", "xsp" });
            Dict.Add("种植箱", new string[] { "zhongzhixiang", "zzx" });
            Dict.Add("塑料花", new string[] { "suliaohua", "slh" });
            Dict.Add("塑料砖", new string[] { "suliaozhuan", "slz" });
            Dict.Add("安全门", new string[] { "anquanmen", "aqm" });
            Dict.Add("展厅门", new string[] { "zhantingmen", "ztm" });
            Dict.Add("大厅门", new string[] { "datingmen", "dtm" });
            Dict.Add("聚合物压塑器", new string[] { "juhewuyasuqi", "jhwysq" });
            Dict.Add("电控站", new string[] { "diankongzhan", "dkz" });
            Dict.Add("大型变压器", new string[] { "daxingbianyaqi", "dxbyq" });
            Dict.Add("变压器", new string[] { "bianyaqi", "byq" });
            Dict.Add("机械气闸", new string[] { "jixieqizha", "jxqz" });
            Dict.Add("气压电闸", new string[] { "qiyadianzha", "qydz" });
            Dict.Add("液压电闸", new string[] { "yeyadianzha", "yydz" });
            Dict.Add("破旧的沙滩椅", new string[] { "pojiudeshatanyi", "pjdsty" });
            Dict.Add("旅行海报", new string[] { "lvxinghaibao", "lxhb" });
            Dict.Add("声学艺术镶板", new string[] { "shengxueyishuxiangban", "sxysxb" });
            Dict.Add("时钟", new string[] { "shizhong", "sz" });
            Dict.Add("衣架", new string[] { "yijia", "yj" });
            Dict.Add("电脑桌", new string[] { "diannaozhuo", "dnz" });
            Dict.Add("电子显示屏", new string[] { "dianzixianshiping", "dzxsp" });
            Dict.Add("服务推车", new string[] { "fuwutuiche", "fwtc" });
            Dict.Add("损坏的电梯", new string[] { "sunhuaidedianti", "shddt" });
            Dict.Add("场外储物柜", new string[] { "changwaichuwugui", "cwcwg" });
            Dict.Add("预制长架子", new string[] { "yuzhizhangjiazi", "yzzjz" });
            Dict.Add("预制架子", new string[] { "yuzhijiazi", "yzjz" });
            Dict.Add("大厅椅子", new string[] { "datingyizi", "dtyz" });
            Dict.Add("枝形吊灯", new string[] { "zhixingdiaodeng", "zxdd" });
            Dict.Add("大厅沙发", new string[] { "datingshafa", "dtsf" });
            Dict.Add("主管的桌子", new string[] { "zhuguandezhuozi", "zgdzz" });
            Dict.Add("档案柜", new string[] { "dangangui", "dag" });
            Dict.Add("灯具", new string[] { "dengju", "dj" });
            Dict.Add("风景画", new string[] { "fengjinghua", "fjh" });
            Dict.Add("庄严丰碑", new string[] { "zhuangyanfengbei", "zyfb" });
            Dict.Add("咖啡桌", new string[] { "kafeizhuo", "kfz" });
            Dict.Add("办公室植物", new string[] { "bangongshizhiwu", "bgszw" });
            Dict.Add("博士学位证书", new string[] { "boshixueweizhengshu", "bsxwzs" });
            Dict.Add("镜子", new string[] { "jingzi", "jz" });
            Dict.Add("搪瓷水槽", new string[] { "tangcishuicao", "tcsc" });
            Dict.Add("卫生纸架", new string[] { "weishengzhijia", "wszj" });
            Dict.Add("天花板机器人", new string[] { "tianhuabanjiqiren", "thbjqr" });
            Dict.Add("解剖海报", new string[] { "jiepouhaibao", "jphb" });
            Dict.Add("机械研究桌", new string[] { "jixieyanjiuzhuo", "jxyjz" });
            Dict.Add("电脑讲台", new string[] { "diannaojiangtai", "dnjt" });
            Dict.Add("损坏的灭火器", new string[] { "sunhuaidemiehuoqi", "shdmhq" });
            Dict.Add("急救包", new string[] { "jijiubao", "jjb" });
            Dict.Add("翻盖手机", new string[] { "fangaishouji", "fgsj" });
            Dict.Add("机械臂", new string[] { "jixiebi", "jxb" });
            Dict.Add("小型冰柜", new string[] { "xiaoxingbinggui", "xxbg" });
            Dict.Add("手部扫描仪", new string[] { "shoubusaomiaoyi", "sbsmy" });
            Dict.Add("大脑罐", new string[] { "danaoguan", "dng" });
            Dict.Add("样品罐", new string[] { "yangpinguan", "ypg" });
            Dict.Add("实验室桌", new string[] { "shiyanshizhuo", "sysz" });
            Dict.Add("实验室墙面", new string[] { "shiyanshiqiangmian", "sysqm" });
            Dict.Add("实验室窗户", new string[] { "shiyanshichuanghu", "sysch" });
            Dict.Add("纸巾盒", new string[] { "zhijinhe", "zjh" });
            Dict.Add("挂图", new string[] { "guatu", "gt" });
            Dict.Add("死亡的植物", new string[] { "siwangdezhiwu", "swdzw" });
            Dict.Add("架子", new string[] { "jiazi", "jz" });
            Dict.Add("壁橱", new string[] { "bichu", "bc" });
            Dict.Add("工具箱", new string[] { "gongjuxiang", "gjx" });
            Dict.Add("工具架", new string[] { "gongjujia", "gjj" });
            Dict.Add("垃圾桶", new string[] { "lajitong", "ljt" });
            Dict.Add("墙面", new string[] { "qiangmian", "qm" });
            Dict.Add("展厅椅", new string[] { "zhantingyi", "zty" });
            Dict.Add("展厅沙发", new string[] { "zhantingshafa", "ztsf" });
            Dict.Add("折叠床", new string[] { "zhediechuang", "zdc" });
            Dict.Add("接待前台", new string[] { "jiedaiqiantai", "jdqt" });
            Dict.Add("骨骼模型", new string[] { "gugemoxing", "ggmx" });
            Dict.Add("撞毁的卫星", new string[] { "zhuanghuideweixing", "zhdwx" });
            Dict.Add("失事的卫星", new string[] { "shishideweixing", "ssdwx" });
            Dict.Add("粉碎的卫星", new string[] { "fensuideweixing", "fsdwx" });
            Dict.Add("桌子", new string[] { "zhuozi", "zz" });
            Dict.Add("盆栽植物", new string[] { "penzaizhiwu", "pzzw" });
            Dict.Add("辐射灯", new string[] { "fushedeng", "fsd" });
            Dict.Add("星际发射器", new string[] { "xingjifasheqi", "xjfsq" });
            Dict.Add("载货拆包器", new string[] { "zaihuochaibaoqi", "zhcbq" });
            Dict.Add("梳理站", new string[] { "shulizhan", "slz" });
            Dict.Add("口粮箱", new string[] { "kouliangxiang", "klx" });
            Dict.Add("潮汐涡轮机", new string[] { "chaoxiwolunji", "cxwlj" });
            Dict.Add("冰箱", new string[] { "bingxiang", "bx" });
            Dict.Add("远程作业坞", new string[] { "yuanchengzuoyewu", "yczyw" });
            Dict.Add("作业坞 {ID}", new string[] { "zuoyewu {ID}", "zyw {ID}" });
            Dict.Add("远程控制器", new string[] { "yuanchengkongzhiqi", "yckzq" });
            Dict.Add("研究站", new string[] { "yanjiuzhan", "yjz" });
            Dict.Add("研究舱", new string[] { "yanjiucang", "yjc" });
            Dict.Add("技能涤除器", new string[] { "jinengdichuqi", "jndcq" });
            Dict.Add("机器驾驶舱", new string[] { "jiqijiashicang", "jqjsc" });
            Dict.Add("碎石机", new string[] { "suishiji", "ssj" });
            Dict.Add("火箭驾驶舱", new string[] { "huojianjiashicang", "hjjsc" });
            Dict.Add("火箭控制台", new string[] { "huojiankongzhitai", "hjkzt" });
            Dict.Add("火箭", new string[] { "huojian", "hj" });
            Dict.Add("火箭窗户", new string[] { "huojianchuanghu", "hjch" });
            Dict.Add("气体输入配件", new string[] { "qitishurupeijian", "qtsrpj" });
            Dict.Add("太空员舱气体输入端口", new string[] { "taikongyuancangqitishuruduankou", "tkycqtsrdk" });
            Dict.Add("气体输出配件", new string[] { "qitishuchupeijian", "qtscpj" });
            Dict.Add("太空员舱气体输出端口", new string[] { "taikongyuancangqitishuchuduankou", "tkycqtscdk" });
            Dict.Add("液体输入配件", new string[] { "yetishurupeijian", "ytsrpj" });
            Dict.Add("太空员舱液体输入端口", new string[] { "taikongyuancangyetishuruduankou", "tkycytsrdk" });
            Dict.Add("液体输出配件", new string[] { "yetishuchupeijian", "ytscpj" });
            Dict.Add("太空员舱液体输出端口", new string[] { "taikongyuancangyetishuchuduankou", "tkycytscdk" });
            Dict.Add("电源插座配件", new string[] { "dianyuanchazuopeijian", "dyczpj" });
            Dict.Add("运输存放配件", new string[] { "yunshucunfangpeijian", "yscfpj" });
            Dict.Add("运输装载配件", new string[] { "yunshuzhuangzaipeijian", "yszzpj" });
            Dict.Add("拓荒者部署舱", new string[] { "tuohuangzhebushucang", "thzbsc" });
            Dict.Add("火箭墙体", new string[] { "huojianqiangti", "hjqt" });
            Dict.Add("技能公示板", new string[] { "jinenggongshiban", "jngsb" });
            Dict.Add("硫化器", new string[] { "liuhuaqi", "lhq" });
            Dict.Add("铁锈脱氧机", new string[] { "tiexiutuoyangji", "txtyj" });
            Dict.Add("桑拿房", new string[] { "sangnafang", "snf" });
            Dict.Add("制图舱", new string[] { "zhitucang", "ztc" });
            Dict.Add("侦察着陆器", new string[] { "zhenchazhuoluqi", "zczlq" });
            Dict.Add("侦察舱", new string[] { "zhenchacang", "zcc" });
            Dict.Add("侦察窝", new string[] { "zhenchawo", "zcw" });
            Dict.Add("大型雕塑块", new string[] { "daxingdiaosukuai", "dxdsk" });
            Dict.Add("储物柜", new string[] { "chuwugui", "cwg" });
            Dict.Add("修剪站", new string[] { "xiujianzhan", "xjz" });
            Dict.Add("陈列架", new string[] { "chenliejia", "clj" });
            Dict.Add("淋浴隔间", new string[] { "linyugejian", "lygj" });
            Dict.Add("单人游戏机台", new string[] { "danrenyouxijitai", "dryxjt" });
            Dict.Add("泥浆分离器", new string[] { "nijiangfenliqi", "njflq" });
            Dict.Add("袖珍放电器", new string[] { "xiuzhenfangdianqi", "xzfdq" });
            Dict.Add("小型固体氧化剂舱", new string[] { "xiaoxinggutiyanghuajicang", "xxgtyhjc" });
            Dict.Add("雕塑块", new string[] { "diaosukuai", "dsk" });
            Dict.Add("熏炉", new string[] { "xunlu", "xl" });
            Dict.Add("雪砖", new string[] { "xuezhuan", "xz" });
            Dict.Add("汽水机", new string[] { "qishuiji", "qsj" });
            Dict.Add("太阳能板", new string[] { "taiyangnengban", "tynb" });
            Dict.Add("太阳能舱", new string[] { "taiyangnengcang", "tync" });
            Dict.Add("固体燃料推进器", new string[] { "gutiranliaotuijinqi", "gtrltjq" });
            Dict.Add("运输轨道", new string[] { "yunshuguidao", "ysgd" });
            Dict.Add("运输轨桥", new string[] { "yunshuguiqiao", "ysgq" });
            Dict.Add("运输轨道病菌传感器", new string[] { "yunshuguidaobingjunchuanganqi", "ysgdbjcgq" });
            Dict.Add("运输轨道元素传感器", new string[] { "yunshuguidaoyuansuchuanganqi", "ysgdyscgq" });
            Dict.Add("运输装载器", new string[] { "yunshuzhuangzaiqi", "yszzq" });
            Dict.Add("运输存放器", new string[] { "yunshucunfangqi", "yscfq" });
            Dict.Add("运输轨道温度传感器", new string[] { "yunshuguidaowenduchuanganqi", "ysgdwdcgq" });
            Dict.Add("固体筛选器", new string[] { "gutishaixuanqi", "gtsxq" });
            Dict.Add("轨道计量器", new string[] { "guidaojiliangqi", "gdjlq" });
            Dict.Add("轨道截断器", new string[] { "guidaojieduanqi", "gdjdq" });
            Dict.Add("自动清扫器", new string[] { "zidongqingsaoqi", "zdqsq" });
            Dict.Add("轨道滑槽", new string[] { "guidaohuacao", "gdhc" });
            Dict.Add("空间加热器", new string[] { "kongjianjiareqi", "kjjrq" });
            Dict.Add("生物货舱", new string[] { "shengwuhuocang", "swhc" });
            Dict.Add("小动物货舱", new string[] { "xiaodongwuhuocang", "xdwhc" });
            Dict.Add("香料研磨器", new string[] { "xiangliaoyanmoqi", "xlymq" });
            Dict.Add("蛞蝓蛋", new string[] { "kuoyudan", "kyd" });
            Dict.Add("电弧蛞蝓", new string[] { "dianhukuoyu", "dhky" });
            Dict.Add("蒸汽引擎", new string[] { "zhengqiyinqing", "zqyq" });
            Dict.Add("[弃用] 蒸汽涡轮机", new string[] { "[qiyong] zhengqiwolunji", "[qy] zqwlj" });
            Dict.Add("蒸汽涡轮机", new string[] { "zhengqiwolunji", "zqwlj" });
            Dict.Add("贴纸炸弹", new string[] { "tiezhizhadan", "tzzd" });
            Dict.Add("存储箱", new string[] { "cunchuxiang", "ccx" });
            Dict.Add("智能存储箱", new string[] { "zhinengcunchuxiang", "znccx" });
            Dict.Add("存储砖", new string[] { "cunchuzhuan", "ccz" });
            Dict.Add("升华站", new string[] { "shenghuazhan", "shz" });
            Dict.Add("糖素引擎", new string[] { "tangsuyinqing", "tsyq" });
            Dict.Add("太空服锻造台", new string[] { "taikongfuduanzaotai", "tkfdzt" });
            Dict.Add("气压服存放柜", new string[] { "qiyafucunfanggui", "qyfcfg" });
            Dict.Add("气压服检查站", new string[] { "qiyafujianchazhan", "qyfjcz" });
            Dict.Add("日光灯", new string[] { "riguangdeng", "rgd" });
            Dict.Add("分子熔炉", new string[] { "fenzironglu", "fzrl" });
            Dict.Add("寿司台", new string[] { "shousitai", "sst" });
            Dict.Add("扫扫基站", new string[] { "saosaojizhan", "ssjz" });
            Dict.Add("{0}的基站", new string[] { "{0}dejizhan", "{0}djz" });
            Dict.Add("电闸", new string[] { "dianzha", "dz" });
            Dict.Add("共线电话", new string[] { "gongxiandianhua", "gxdh" });
            Dict.Add("传送台", new string[] { "chuansongtai", "cst" });
            Dict.Add("温控开关", new string[] { "wenkongkaiguan", "wkkg" });
            Dict.Add("时间裂口开放器", new string[] { "shijianliekoukaifangqi", "sjlkkfq" });
            Dict.Add("变温板", new string[] { "bianwenban", "bwb" });
            Dict.Add("砖块", new string[] { "zhuankuai", "zk" });
            Dict.Add("观光舱", new string[] { "guanguangcang", "ggc" });
            Dict.Add("运载管道", new string[] { "yunzaiguandao", "yzgd" });
            Dict.Add("运载管道入口", new string[] { "yunzaiguandaorukou", "yzgdrk" });
            Dict.Add("运载管道渡口", new string[] { "yunzaiguandaodukou", "yzgddk" });
            Dict.Add("空火箭舱", new string[] { "konghuojiancang", "khjc" });
            Dict.Add("呼吸站", new string[] { "huxizhan", "hxz" });
            Dict.Add("水生小动物公寓", new string[] { "shuishengxiaodongwugongyu", "ssxdwgy" });
            Dict.Add("水生小动物直饮器", new string[] { "shuishengxiaodongwuzhiyinqi", "ssxdwzyq" });
            Dict.Add("水生挤奶站", new string[] { "shuishengjinaizhan", "ssjnz" });
            Dict.Add("水生梳理站", new string[] { "shuishengshulizhan", "ssslz" });
            Dict.Add("水生修剪站", new string[] { "shuishengxiujianzhan", "ssxjz" });
            Dict.Add("海洋钻机", new string[] { "haiyangzuanji", "hyzj" });
            Dict.Add("铀素离心机", new string[] { "yousulixinji", "yslxj" });
            Dict.Add("自动贩卖机", new string[] { "zidongfanmaiji", "zdfmj" });
            Dict.Add("垂直风洞", new string[] { "chuizhifengdong", "czfd" });
            Dict.Add("墙排马桶", new string[] { "qiangpaimatong", "qpmt" });
            Dict.Add("供给传送器输出端", new string[] { "gongjichuansongqishuchuduan", "gjcsqscd" });
            Dict.Add("供给传送器输入端", new string[] { "gongjichuansongqishuruduan", "gjcsqsrd" });
            Dict.Add("传送发射器", new string[] { "chuansongfasheqi", "csfsq" });
            Dict.Add("传送接收器", new string[] { "chuansongjieshouqi", "csjsq" });
            Dict.Add("洗手盆", new string[] { "xishoupen", "xsp" });
            Dict.Add("洗手池", new string[] { "xishouchi", "xsc" });
            Dict.Add("饮水机", new string[] { "yinshuiji", "ysj" });
            Dict.Add("净水器", new string[] { "jingshuiqi", "jsq" });
            Dict.Add("宽液培砖", new string[] { "kuanyepeizhuan", "kypz" });
            Dict.Add("电线", new string[] { "dianxian", "dx" });
            Dict.Add("电线桥", new string[] { "dianxianqiao", "dxq" });
            Dict.Add("高负荷电线接合板", new string[] { "gaofuhedianxianjieheban", "gfhdxjhb" });
            Dict.Add("导线", new string[] { "daoxian", "dx" });
            Dict.Add("导线桥", new string[] { "daoxianqiao", "dxq" });
            Dict.Add("高负荷导线接合板", new string[] { "gaofuhedaoxianjieheban", "gfhdxjhb" });
            Dict.Add("高负荷导线", new string[] { "gaofuhedaoxian", "gfhdx" });
            Dict.Add("绝缘导线", new string[] { "jueyuandaoxian", "jydx" });
            Dict.Add("绝缘导线桥", new string[] { "jueyuandaoxianqiao", "jydxq" });
            Dict.Add("柳条门", new string[] { "liutiaomen", "ltm" });
            Dict.Add("木材燃烧器", new string[] { "mucairanshaoqi", "mcrsq" });
            Dict.Add("木雕塑块", new string[] { "mudiaosukuai", "mdsk" });
            Dict.Add("柴堆", new string[] { "chaidui", "cd" });
            Dict.Add("木砖", new string[] { "muzhuan", "mz" });
            Dict.Add("气凝胶", new string[] { "qiningjiao", "qnj" });
            Dict.Add("藻类", new string[] { "zaolei", "zl" });
            Dict.Add("铝", new string[] { "lv", "l" });
            Dict.Add("气态铝", new string[] { "qitailv", "qtl" });
            Dict.Add("铝矿", new string[] { "lvkuang", "lk" });
            Dict.Add("琥珀", new string[] { "hupo", "hp" });
            Dict.Add("玄武岩", new string[] { "xuanwuyan", "xwy" });
            Dict.Add("沥青", new string[] { "liqing", "lq" });
            Dict.Add("漂白石", new string[] { "piaobaishi", "pbs" });
            Dict.Add("桶装水", new string[] { "tongzhuangshui", "tzs" });
            Dict.Add("红砖", new string[] { "hongzhuan", "hz" });
            Dict.Add("浓盐水", new string[] { "nongyanshui", "nys" });
            Dict.Add("浓盐冰", new string[] { "nongyanbing", "nyb" });
            Dict.Add("煤炭", new string[] { "meitan", "mt" });
            Dict.Add("二氧化碳", new string[] { "eryanghuatan", "eyht" });
            Dict.Add("碳纤维", new string[] { "tanxianwei", "txw" });
            Dict.Add("气态碳", new string[] { "qitaitan", "qtt" });
            Dict.Add("水泥", new string[] { "shuini", "sn" });
            Dict.Add("水泥混合料", new string[] { "shuinihunheliao", "snhhl" });
            Dict.Add("陶瓷", new string[] { "taoci", "tc" });
            Dict.Add("液态氯", new string[] { "yetailv", "ytl" });
            Dict.Add("氯气", new string[] { "lvqi", "lq" });
            Dict.Add("朱砂矿", new string[] { "zhushakuang", "zsk" });
            Dict.Add("粘土", new string[] { "niantu", "nt" });
            Dict.Add("钴", new string[] { "gu", "g" });
            Dict.Add("气态钴", new string[] { "qitaigu", "qtg" });
            Dict.Add("钴矿", new string[] { "gukuang", "gk" });
            Dict.Add("复合物", new string[] { "fuhewu", "fhw" });
            Dict.Add("污染氧", new string[] { "wuranyang", "wry" });
            Dict.Add("铜", new string[] { "tong", "t" });
            Dict.Add("气态铜", new string[] { "qitaitong", "qtt" });
            Dict.Add("壳灰岩", new string[] { "kehuiyan", "khy" });
            Dict.Add("珊瑚质", new string[] { "shanhuzhi", "shz" });
            Dict.Add("堆芯熔融物", new string[] { "duixinrongrongwu", "dxrrw" });
            Dict.Add("遗传生物软泥", new string[] { "yichuanshengwuruanni", "ycswrn" });
            Dict.Add("原油", new string[] { "yuanyou", "yy" });
            Dict.Add("碎冰", new string[] { "suibing", "sb" });
            Dict.Add("碎岩", new string[] { "suiyan", "sy" });
            Dict.Add("铜矿", new string[] { "tongkuang", "tk" });
            Dict.Add("贫铀", new string[] { "pinyou", "py" });
            Dict.Add("钻石", new string[] { "zuanshi", "zs" });
            Dict.Add("泥土", new string[] { "nitu", "nt" });
            Dict.Add("污染冰", new string[] { "wuranbing", "wrb" });
            Dict.Add("污染水", new string[] { "wuranshui", "wrs" });
            Dict.Add("银金矿", new string[] { "yinjinkuang", "yjk" });
            Dict.Add("浓缩铀", new string[] { "nongsuoyou", "nsy" });
            Dict.Add("乙醇", new string[] { "yichun", "yc" });
            Dict.Add("气态乙醇", new string[] { "qitaiyichun", "qtyc" });
            Dict.Add("胶合板", new string[] { "jiaoheban", "jhb" });
            Dict.Add("核尘埃", new string[] { "hechenai", "hca" });
            Dict.Add("肥料", new string[] { "feiliao", "fl" });
            Dict.Add("卵浆", new string[] { "luanjiang", "lj" });
            Dict.Add("凝冻卵浆", new string[] { "ningdongluanjiang", "ndlj" });
            Dict.Add("黄铁矿", new string[] { "huangtiekuang", "htk" });
            Dict.Add("化石", new string[] { "huashi", "hs" });
            Dict.Add("凝冻墨汁", new string[] { "ningdongmozhi", "ndmz" });
            Dict.Add("凝冻植物润滑油", new string[] { "ningdongzhiwurunhuayou", "ndzwrhy" });
            Dict.Add("富勒烯", new string[] { "fuleixi", "flx" });
            Dict.Add("方铅矿", new string[] { "fangqiankuang", "fqk" });
            Dict.Add("玻璃", new string[] { "boli", "bl" });
            Dict.Add("金", new string[] { "jin", "j" });
            Dict.Add("金汞齐", new string[] { "jingongqi", "jgq" });
            Dict.Add("气态金", new string[] { "qitaijin", "qtj" });
            Dict.Add("花岗岩", new string[] { "huagangyan", "hgy" });
            Dict.Add("石墨", new string[] { "shimo", "sm" });
            Dict.Add("固态粘渣油", new string[] { "gutaizhanzhayou", "gtzzy" });
            Dict.Add("塑料质", new string[] { "suliaozhi", "slz" });
            Dict.Add("氦气", new string[] { "haiqi", "hq" });
            Dict.Add("氢气", new string[] { "qingqi", "qq" });
            Dict.Add("冰", new string[] { "bing", "b" });
            Dict.Add("火成岩", new string[] { "huochengyan", "hcy" });
            Dict.Add("鱿鱼墨汁", new string[] { "youyumozhi", "yymz" });
            Dict.Add("铱", new string[] { "yi", "y" });
            Dict.Add("气态铱", new string[] { "qitaiyi", "qty" });
            Dict.Add("铁", new string[] { "tie", "t" });
            Dict.Add("气态铁", new string[] { "qitaitie", "qtt" });
            Dict.Add("铁矿", new string[] { "tiekuang", "tk" });
            Dict.Add("异构树液", new string[] { "yigoushuye", "ygsy" });
            Dict.Add("深渊晶石", new string[] { "shenyuanjingshi", "syjs" });
            Dict.Add("胶乳", new string[] { "jiaoru", "jr" });
            Dict.Add("铅", new string[] { "qian", "q" });
            Dict.Add("气态铅", new string[] { "qitaiqian", "qtq" });
            Dict.Add("石灰", new string[] { "shihui", "sh" });
            Dict.Add("液态二氧化碳", new string[] { "yetaieryanghuatan", "yteyht" });
            Dict.Add("粘渣油", new string[] { "zhanzhayou", "zzy" });
            Dict.Add("液态氦", new string[] { "yetaihai", "yth" });
            Dict.Add("液态氢", new string[] { "yetaiqing", "ytq" });
            Dict.Add("液态甲烷", new string[] { "yetaijiawan", "ytjw" });
            Dict.Add("液态氧", new string[] { "yetaiyang", "yty" });
            Dict.Add("液态磷", new string[] { "yetailin", "ytl" });
            Dict.Add("液态丙烷", new string[] { "yetaibingwan", "ytbw" });
            Dict.Add("液态硫", new string[] { "yetailiu", "ytl" });
            Dict.Add("镁铁质岩", new string[] { "meitiezhiyan", "mtzy" });
            Dict.Add("岩浆", new string[] { "yanjiang", "yj" });
            Dict.Add("汞", new string[] { "gong", "g" });
            Dict.Add("汞蒸气", new string[] { "gongzhengqi", "gzq" });
            Dict.Add("天然气", new string[] { "tianranqi", "trq" });
            Dict.Add("咸乳", new string[] { "xianru", "xr" });
            Dict.Add("咸乳蜡", new string[] { "xianrula", "xrl" });
            Dict.Add("凝冻咸乳", new string[] { "ningdongxianru", "ndxr" });
            Dict.Add("熔融铝", new string[] { "rongronglv", "rrl" });
            Dict.Add("熔融碳", new string[] { "rongrongtan", "rrt" });
            Dict.Add("熔融钴", new string[] { "rongronggu", "rrg" });
            Dict.Add("熔融铜", new string[] { "rongrongtong", "rrt" });
            Dict.Add("熔融玻璃", new string[] { "rongrongboli", "rrbl" });
            Dict.Add("熔融金", new string[] { "rongrongjin", "rrj" });
            Dict.Add("熔融铱", new string[] { "rongrongyi", "rry" });
            Dict.Add("熔融铁", new string[] { "rongrongtie", "rrt" });
            Dict.Add("熔融铅", new string[] { "rongrongqian", "rrq" });
            Dict.Add("熔融镍", new string[] { "rongrongnie", "rrn" });
            Dict.Add("熔融铌", new string[] { "rongrongni", "rrn" });
            Dict.Add("熔融盐", new string[] { "rongrongyan", "rry" });
            Dict.Add("熔融钢", new string[] { "rongronggang", "rrg" });
            Dict.Add("熔融蔗糖", new string[] { "rongrongzhetang", "rrzt" });
            Dict.Add("熔融合成气", new string[] { "rongronghechengqi", "rrhcq" });
            Dict.Add("熔融钨", new string[] { "rongrongwu", "rrw" });
            Dict.Add("熔融二硒化钨", new string[] { "rongrongerxihuawu", "rrexhw" });
            Dict.Add("熔融铀", new string[] { "rongrongyou", "rry" });
            Dict.Add("熔融锌", new string[] { "rongrongxin", "rrx" });
            Dict.Add("粘蛋白", new string[] { "zhandanbai", "zdb" });
            Dict.Add("泥巴", new string[] { "niba", "nb" });
            Dict.Add("污染浓盐水", new string[] { "wurannongyanshui", "wrnys" });
            Dict.Add("污染浓盐冰", new string[] { "wurannongyanbing", "wrnyb" });
            Dict.Add("液态石脑油", new string[] { "yetaishinaoyou", "ytsny" });
            Dict.Add("树脂", new string[] { "shuzhi", "sz" });
            Dict.Add("固态树脂", new string[] { "gutaishuzhi", "gtsz" });
            Dict.Add("镍", new string[] { "nie", "n" });
            Dict.Add("气态镍", new string[] { "qitainie", "qtn" });
            Dict.Add("镍矿", new string[] { "niekuang", "nk" });
            Dict.Add("铌", new string[] { "ni", "n" });
            Dict.Add("气态铌", new string[] { "qitaini", "qtn" });
            Dict.Add("液态核废料", new string[] { "yetaihefeiliao", "ythfl" });
            Dict.Add("黑曜石", new string[] { "heiyaoshi", "hys" });
            Dict.Add("氧气", new string[] { "yangqi", "yq" });
            Dict.Add("氧石", new string[] { "yangshi", "ys" });
            Dict.Add("粘胶木材", new string[] { "zhanjiaomucai", "zjmc" });
            Dict.Add("珍珠", new string[] { "zhenzhu", "zz" });
            Dict.Add("泥炭", new string[] { "nitan", "nt" });
            Dict.Add("石油", new string[] { "shiyou", "sy" });
            Dict.Add("磷酸盐结晶", new string[] { "linsuanyanjiejing", "lsyjj" });
            Dict.Add("磷矿", new string[] { "linkuang", "lk" });
            Dict.Add("精炼磷", new string[] { "jinglianlin", "jll" });
            Dict.Add("气态磷", new string[] { "qitailin", "qtl" });
            Dict.Add("植物润滑油", new string[] { "zhiwurunhuayou", "zwrhy" });
            Dict.Add("塑料", new string[] { "suliao", "sl" });
            Dict.Add("绿藻浮渣", new string[] { "lvzaofuzha", "lzfz" });
            Dict.Add("丙烷", new string[] { "bingwan", "bw" });
            Dict.Add("镭", new string[] { "lei", "l" });
            Dict.Add("精炼碳", new string[] { "jingliantan", "jlt" });
            Dict.Add("生物柴油", new string[] { "shengwuchaiyou", "swcy" });
            Dict.Add("浮土", new string[] { "futu", "ft" });
            Dict.Add("树液", new string[] { "shuye", "sy" });
            Dict.Add("气态岩", new string[] { "qitaiyan", "qty" });
            Dict.Add("橡胶", new string[] { "xiangjiao", "xj" });
            Dict.Add("铁锈", new string[] { "tiexiu", "tx" });
            Dict.Add("盐", new string[] { "yan", "y" });
            Dict.Add("气态盐", new string[] { "qitaiyan", "qty" });
            Dict.Add("盐水", new string[] { "yanshui", "ys" });
            Dict.Add("沙子", new string[] { "shazi", "sz" });
            Dict.Add("砂水泥", new string[] { "shashuini", "ssn" });
            Dict.Add("砂岩", new string[] { "shayan", "sy" });
            Dict.Add("沉积岩", new string[] { "chenjiyan", "cjy" });
            Dict.Add("页岩", new string[] { "yeyan", "yy" });
            Dict.Add("粉砂岩", new string[] { "fenshayan", "fsy" });
            Dict.Add("建筑板材", new string[] { "jianzhubancai", "jzbc" });
            Dict.Add("菌泥", new string[] { "junni", "jn" });
            Dict.Add("雪", new string[] { "xue", "x" });
            Dict.Add("固态二氧化碳", new string[] { "gutaieryanghuatan", "gteyht" });
            Dict.Add("固态氯", new string[] { "gutailv", "gtl" });
            Dict.Add("固态原油", new string[] { "gutaiyuanyou", "gtyy" });
            Dict.Add("固态乙醇", new string[] { "gutaiyichun", "gtyc" });
            Dict.Add("固态氢", new string[] { "gutaiqing", "gtq" });
            Dict.Add("固态汞", new string[] { "gutaigong", "gtg" });
            Dict.Add("固态甲烷", new string[] { "gutaijiawan", "gtjw" });
            Dict.Add("凝冻粘蛋白", new string[] { "ningdongzhandanbai", "ndzdb" });
            Dict.Add("固态石脑油", new string[] { "gutaishinaoyou", "gtsny" });
            Dict.Add("固态核废料", new string[] { "gutaihefeiliao", "gthfl" });
            Dict.Add("固态氧", new string[] { "gutaiyang", "gty" });
            Dict.Add("固态石油", new string[] { "gutaishiyou", "gtsy" });
            Dict.Add("固态丙烷", new string[] { "gutaibingwan", "gtbw" });
            Dict.Add("固态树液", new string[] { "gutaishuye", "gtsy" });
            Dict.Add("固态超级冷却剂", new string[] { "gutaichaojilengqueji", "gtcjlqj" });
            Dict.Add("固态合成气", new string[] { "gutaihechengqi", "gthcq" });
            Dict.Add("固态粘性凝胶", new string[] { "gutaizhanxingningjiao", "gtzxnj" });
            Dict.Add("高硫天然气", new string[] { "gaoliutianranqi", "gltrq" });
            Dict.Add("蒸汽", new string[] { "zhengqi", "zq" });
            Dict.Add("钢", new string[] { "gang", "g" });
            Dict.Add("气态钢", new string[] { "qitaigang", "qtg" });
            Dict.Add("蔗糖", new string[] { "zhetang", "zt" });
            Dict.Add("花蜜", new string[] { "huami", "hm" });
            Dict.Add("硫", new string[] { "liu", "l" });
            Dict.Add("硫蒸气", new string[] { "liuzhengqi", "lzq" });
            Dict.Add("超级冷却剂", new string[] { "chaojilengqueji", "cjlqj" });
            Dict.Add("气态超级冷却剂", new string[] { "qitaichaojilengqueji", "qtcjlqj" });
            Dict.Add("隔热质", new string[] { "gerezhi", "grz" });
            Dict.Add("合成气", new string[] { "hechengqi", "hcq" });
            Dict.Add("动物油脂", new string[] { "dongwuyouzhi", "dwyz" });
            Dict.Add("导热质", new string[] { "daorezhi", "drz" });
            Dict.Add("测试元素", new string[] { "ceshiyuansu", "csys" });
            Dict.Add("污染泥", new string[] { "wuranni", "wrn" });
            Dict.Add("污染土", new string[] { "wurantu", "wrt" });
            Dict.Add("钨", new string[] { "wu", "w" });
            Dict.Add("二硒化钨", new string[] { "erxihuawu", "exhw" });
            Dict.Add("气态二硒化钨", new string[] { "qitaierxihuawu", "qtexhw" });
            Dict.Add("气态钨", new string[] { "qitaiwu", "qtw" });
            Dict.Add("中子质", new string[] { "zhongzizhi", "zzz" });
            Dict.Add("铀矿", new string[] { "youkuang", "yk" });
            Dict.Add("真空", new string[] { "zhenkong", "zk" });
            Dict.Add("粘性凝胶流体", new string[] { "zhanxingningjiaoliuti", "zxnjlt" });
            Dict.Add("虚空", new string[] { "xukong", "xk" });
            Dict.Add("水", new string[] { "shui", "s" });
            Dict.Add("黑钨矿", new string[] { "heiwukuang", "hwk" });
            Dict.Add("木材", new string[] { "mucai", "mc" });
            Dict.Add("黄饼", new string[] { "huangbing", "hb" });
            Dict.Add("锌", new string[] { "xin", "x" });
            Dict.Add("气态锌", new string[] { "qitaixin", "qtx" });
            Dict.Add("锌矿", new string[] { "xinkuang", "xk" });
            Dict.Add("细胞粘合剂", new string[] { "xibaonianheji", "xbnhj" });



            return Dict;
        }
    }
}
